# My Jupyter Notebook on IBM Watson Studio

### Felix Ehuren
Data Analyst

###### I am interested in data science because of high demands of data scientist and also growth in career and salaries

### My code in the next cell is intended to display ths sum of squares of numbers

In [12]:
print(4**2 + 5**2)

41

***
[Chelsea](https://www.chelseafc.com 'Become a chelsea fun')

| Name | Age | Genda| Marrital Status|
| ---  |----- |---- | ----- |
| ---  |----- |---- | ----- |
| Felix | 38 | Male | Married|
| Julia | 32 | Female | Single|
|Leena| |35  | Female | Married|
|Mark|  |28  | Male| | Mrries|

# Number list
1. 5
2. 10
3. 100
4. 0